---

- name: Install lexicon packages
  apt: name={{ dehydrated_lexicon_packages }}

- name: Copy hook script
  copy:
    dest: /etc/dehydrated/hooks.d/01lexicon
    src: 01lexicon
    owner: root
    group: root
    mode: "0700"
