---

- include_tasks: install.yml
  when: dehydrated_install | bool

- name: Ensure base directory exists
  file:
    dest: "{{ dehydrated_basedir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create wellknown challenge directory
  file:
    path: "{{ dehydrated_wellknown }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: dehydrated_wellknown is defined

- name: Generate dehydrated config
  template:
    dest: /etc/dehydrated/config
    src: config.j2
    owner: root
    group: root
    mode: 0600

- name: Generate dehydrated domains.txt
  copy:
    dest: /etc/dehydrated/domains.txt
    content: "{{ dehydrated_domains }}"
    owner: root
    group: root
    mode: 0600
  notify: run dehydrated

- import_tasks: hooks.yml

- import_tasks: domain_config.yml

- name: Include dns-01-lexicon.yml
  include_tasks: dns-01-lexicon.yml
  when: dehydrated_use_lexicon | bool

- name: Install cronjob
  cron:
    name: dehydrated-renew
    minute: "{{ 59|random(seed=inventory_hostname) }}"
    hour: "{{ 4|random(seed=inventory_hostname) }}"
    user: root
    job: "{{ dehydrated_cronjob_cmd }}{% if dehydrated_cronjob_suffix %} {{ dehydrated_cronjob_suffix }}{% endif %}"
    cron_file: dehydrated
    state: "{{ 'present' if dehydrated_cronjob | bool else 'absent' }}"

- import_tasks: systemd.yml

- import_tasks: registration.yml

- name: Flush handler to force dehydrated run now if neccessary
  meta: flush_handlers
